spring.application.name=analytics
spring.datasource.url=jdbc:snowflake://QDXKKIX-IY55722.snowflakecomputing.com/?db=ANALYTICS_DB&schema=ANALYTICS_SCHEMA&warehouse=ANALYTICS_WH&role=ACCOUNTADMIN&jdbc_query_result_format=json
spring.datasource.username=DEEPCHAN04
spring.datasource.password=Brasil@@1011810118
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver
server.port=8081
