spring.application.name=analytics
spring.datasource.url=jdbc:snowflake://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/?db=${SNOWFLAKE_DB}&schema=${SNOWFLAKE_SCHEMA}&warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}&jdbc_query_result_format=json
spring.datasource.username=${SNOWFLAKE_USER}
spring.datasource.password=${SNOWFLAKE_PASSWORD}
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver
server.port=8081